language: go

sudo: required

go:
  - 1.9.x
  - master

install:
  - go get -v ./...
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - /.*/
